#!/bin/sh

Path=$(pwd)

cp -r /Users/stoddards/Desktop/ProteinDockingScripts $Path 

rm *~

#cd $Path
#ls

cp *.pdb $Path/ProteinDockingScripts

cd ProteinDockingScripts

./DockingPrepforPeptidesShell

cd ProteinDockingScripts

cp *prepfile-proteins.pdb $Path

rm *~

#./$Path/ProteinDockingScripts/DockingPrepforPeptidesShell

#echo $Path

