
#A.2.20 SVS-PDB-FILENAME-EXCHANGE.PY
#READ.line.py separate lines
#This program reads separate lines

import string 
import os
import sys

# This will only work for file names ending with .#.mo.out or the like, where
#the file number is in the 1st from last position in the filename.

print " \n "
print "Removing ANSIOU lines"
print "\n"


#inFile = "result_001.pdb"
inFile = sys.argv[1]
print inFile
inParts = string.split(inFile,".")
print inParts
outParts = inParts[0]
#newparts = string.split(outParts, ".")
#print newparts
#lastparts = newparts[0]
#print lastparts
#print ("%s is running." %inFile)
outName = outParts+"-prepfile.pdb"
print outName	

input = open('%s' %inFile,'r')
# #input = open(Prepare-inputfile.pdb,'r')
#outFile = open("Prepare-input-file.pdb",'a')
# 
#input = open('%s' %inFile,'r')
outFile = open('%s' %outName,'a')

def main():
	

 	for i in range (1, 100000):
 			line = input.readline()
 			if len(line) < 82:
  				if "ATOM"in line:	
  					#line = line.replace(" A   "," B   ")
  					#line = line.replace(" A  "," B  ")
  					
  					line = line.replace("A   ", "A A ")
  					line = line.replace("A   ", "A A ")
  					line = line.replace("A   ", "A A ")
  					line = line.replace("A   ", "A A ")
  					line = line.replace("A   ", "A A ")
  					line = line.replace("A   ", "A A ")
  					line = line.replace("A   ", "A A ")
  					line = line.replace("A   ", "A A ")
  					line = line.replace("A   ", "A A ")
  					line = line.replace("A   ", "A A ")
  					line = line.replace("A   ", "A A ")
  					line = line.replace("A   ", "A A ")
  					
  					line = line.replace("E   ", "E A ")
  					line = line.replace("E   ", "E A ")
  					line = line.replace("E   ", "E A ")
  					line = line.replace("E   ", "E A ")
  					line = line.replace("E   ", "E A ")
  					line = line.replace("E   ", "E A ")
  					line = line.replace("E   ", "E A ")
  					line = line.replace("E   ", "E A ")
  					line = line.replace("E   ", "E A ")
  					line = line.replace("E   ", "E A ")
  					line = line.replace("E   ", "E A ")
  					line = line.replace("E   ", "E A ")
  					
  					line = line.replace("G   ", "G A ")
  					line = line.replace("G   ", "G A ")
  					line = line.replace("G   ", "G A ")
  					line = line.replace("G   ", "G A ")
  					line = line.replace("G   ", "G A ")
  					line = line.replace("G   ", "G A ")
  					line = line.replace("G   ", "G A ")
  					line = line.replace("G   ", "G A ")
  					line = line.replace("G   ", "G A ")
  					line = line.replace("G   ", "G A ")
  					line = line.replace("G   ", "G A ")
  					line = line.replace("G   ", "G A ")
  					
  					line = line.replace("L   ", "L A ")
  					line = line.replace("L   ", "L A ")
  					line = line.replace("L   ", "L A ")
  					line = line.replace("L   ", "L A ")
  					line = line.replace("L   ", "L A ")
  					line = line.replace("L   ", "L A ")
  					line = line.replace("L   ", "L A ")
  					line = line.replace("L   ", "L A ")
  					line = line.replace("L   ", "L A ")
  					line = line.replace("L   ", "L A ")
  					line = line.replace("L   ", "L A ")
  					line = line.replace("L   ", "L A ")
  					
  					line = line.replace("N   ", "N A ")
  					line = line.replace("N   ", "N A ")
  					line = line.replace("N   ", "N A ")
  					line = line.replace("N   ", "N A ")
  					line = line.replace("N   ", "N A ")
  					line = line.replace("N   ", "N A ")
  					line = line.replace("N   ", "N A ")
  					line = line.replace("N   ", "N A ")
  					line = line.replace("N   ", "N A ")
  					line = line.replace("N   ", "N A ")
  					line = line.replace("N   ", "N A ")
  					line = line.replace("N   ", "N A ")
  					
  					line = line.replace("O   ", "O A ")
  					line = line.replace("O   ", "O A ")
  					line = line.replace("O   ", "O A ")
  					line = line.replace("O   ", "O A ")
  					line = line.replace("O   ", "O A ")
  					line = line.replace("O   ", "O A ")
  					line = line.replace("O   ", "O A ")
  					line = line.replace("O   ", "O A ")
  					line = line.replace("O   ", "O A ")
  					line = line.replace("O   ", "O A ")
  					line = line.replace("O   ", "O A ")
  					line = line.replace("O   ", "O A ")
  					
  					line = line.replace("P   ", "P A ")
  					line = line.replace("P   ", "P A ")
  					line = line.replace("P   ", "P A ")
  					line = line.replace("P   ", "P A ")
  					line = line.replace("P   ", "P A ")
  					line = line.replace("P   ", "P A ")
  					line = line.replace("P   ", "P A ")
  					line = line.replace("P   ", "P A ")
  					line = line.replace("P   ", "P A ")
  					line = line.replace("P   ", "P A ")
  					line = line.replace("P   ", "P A ")
  					line = line.replace("P   ", "P A ")
#   					
  					line = line.replace("R   ", "R A ")
  					line = line.replace("R   ", "R A ")
  					line = line.replace("R   ", "R A ")
  					line = line.replace("R   ", "R A ")
  					line = line.replace("R   ", "R A ")
  					line = line.replace("R   ", "R A ")
  					line = line.replace("R   ", "R A ")
  					line = line.replace("R   ", "R A ")
  					line = line.replace("R   ", "R A ")
  					line = line.replace("R   ", "R A ")
  					line = line.replace("R   ", "R A ")
  					line = line.replace("R   ", "R A ")
#   					
  					line = line.replace("S   ", "S A ")
  					line = line.replace("S   ", "S A ")
  					line = line.replace("S   ", "S A ")
  					line = line.replace("S   ", "S A ")
  					line = line.replace("S   ", "S A ")
  					line = line.replace("S   ", "S A ")
  					line = line.replace("S   ", "S A ")
  					line = line.replace("S   ", "S A ")
  					line = line.replace("S   ", "S A ")
  					line = line.replace("S   ", "S A ")
  					line = line.replace("S   ", "S A ")
  					line = line.replace("S   ", "S A ")
  					
  					line = line.replace("T   ", "T A ")
  					line = line.replace("T   ", "T A ")
  					line = line.replace("T   ", "T A ")
  					line = line.replace("T   ", "T A ")
  					line = line.replace("T   ", "T A ")
  					line = line.replace("T   ", "T A ")
  					line = line.replace("T   ", "T A ")
  					line = line.replace("T   ", "T A ")
  					line = line.replace("T   ", "T A ")
  					line = line.replace("T   ", "T A ")
  					line = line.replace("T   ", "T A ")
  					line = line.replace("T   ", "T A ")
  					
  					line = line.replace("U   ", "U A ")
  					line = line.replace("U   ", "U A ")
  					line = line.replace("U   ", "U A ")
  					line = line.replace("U   ", "U A ")
  					line = line.replace("U   ", "U A ")
  					line = line.replace("U   ", "U A ")
  					line = line.replace("U   ", "U A ")
  					line = line.replace("U   ", "U A ")
  					line = line.replace("U   ", "U A ")
  					line = line.replace("U   ", "U A ")
  					line = line.replace("U   ", "U A ")
  					line = line.replace("U   ", "U A ")
  					
  					line = line.replace("Y   ", "Y A ")
  					line = line.replace("Y   ", "Y A ")
  					line = line.replace("Y   ", "Y A ")
  					line = line.replace("Y   ", "Y A ")
  					line = line.replace("Y   ", "Y A ")
  					line = line.replace("Y   ", "Y A ")
  					line = line.replace("Y   ", "Y A ")
  					line = line.replace("Y   ", "Y A ")
  					line = line.replace("Y   ", "Y A ")
  					line = line.replace("Y   ", "Y A ")
  					line = line.replace("Y   ", "Y A ")
  					line = line.replace("Y   ", "Y A ")
  					
  					line = line.replace("A    ", "A A  ")
  					line = line.replace("A    ", "A A  ")
  					line = line.replace("A    ", "A A  ")
  					line = line.replace("A    ", "A A  ")
  					line = line.replace("A    ", "A A  ")
  					line = line.replace("A    ", "A A  ")
  					line = line.replace("A    ", "A A  ")
  					line = line.replace("A    ", "A A  ")
  					line = line.replace("A    ", "A A  ")
  					line = line.replace("A    ", "A A  ")
  					line = line.replace("A    ", "A A  ")
  					line = line.replace("A    ", "A A  ")
  					
  					line = line.replace("E    ", "E A  ")
  					line = line.replace("E    ", "E A  ")
  					line = line.replace("E    ", "E A  ")
  					line = line.replace("E    ", "E A  ")
  					line = line.replace("E    ", "E A  ")
  					line = line.replace("E    ", "E A  ")
  					line = line.replace("E    ", "E A  ")
  					line = line.replace("E    ", "E A  ")
  					line = line.replace("E    ", "E A  ")
  					line = line.replace("E    ", "E A  ")
  					line = line.replace("E    ", "E A  ")
  					line = line.replace("E    ", "E A  ")
  					
  					line = line.replace("G    ", "G A  ")
  					line = line.replace("G    ", "G A  ")
  					line = line.replace("G    ", "G A  ")
  					line = line.replace("G    ", "G A  ")
  					line = line.replace("G    ", "G A  ")
  					line = line.replace("G    ", "G A  ")
  					line = line.replace("G    ", "G A  ")
  					line = line.replace("G    ", "G A  ")
  					line = line.replace("G    ", "G A  ")
  					line = line.replace("G    ", "G A  ")
  					line = line.replace("G    ", "G A  ")
  					line = line.replace("G    ", "G A  ")
  					
  					line = line.replace("L    ", "L A  ")
  					line = line.replace("L    ", "L A  ")
  					line = line.replace("L    ", "L A  ")
  					line = line.replace("L    ", "L A  ")
  					line = line.replace("L    ", "L A  ")
  					line = line.replace("L    ", "L A  ")
  					line = line.replace("L    ", "L A  ")
  					line = line.replace("L    ", "L A  ")
  					line = line.replace("L    ", "L A  ")
  					line = line.replace("L    ", "L A  ")
  					line = line.replace("L    ", "L A  ")
  					line = line.replace("L    ", "L A  ")
  					
  					line = line.replace("N    ", "N A  ")
  					line = line.replace("N    ", "N A  ")
  					line = line.replace("N    ", "N A  ")
  					line = line.replace("N    ", "N A  ")
  					line = line.replace("N    ", "N A  ")
  					line = line.replace("N    ", "N A  ")
  					line = line.replace("N    ", "N A  ")
  					line = line.replace("N    ", "N A  ")
  					line = line.replace("N    ", "N A  ")
  					line = line.replace("N    ", "N A  ")
  					line = line.replace("N    ", "N A  ")
  					line = line.replace("N    ", "N A  ")
  					
  					line = line.replace("O    ", "O A  ")
  					line = line.replace("O    ", "O A  ")
  					line = line.replace("O    ", "O A  ")
  					line = line.replace("O    ", "O A  ")
  					line = line.replace("O    ", "O A  ")
  					line = line.replace("O    ", "O A  ")
  					line = line.replace("O    ", "O A  ")
  					line = line.replace("O    ", "O A  ")
  					line = line.replace("O    ", "O A  ")
  					line = line.replace("O    ", "O A  ")
  					line = line.replace("O    ", "O A  ")
  					line = line.replace("O    ", "O A  ")
  					
  					line = line.replace("P    ", "P A  ")
  					line = line.replace("P    ", "P A  ")
  					line = line.replace("P    ", "P A  ")
  					line = line.replace("P    ", "P A  ")
  					line = line.replace("P    ", "P A  ")
  					line = line.replace("P    ", "P A  ")
  					line = line.replace("P    ", "P A  ")
  					line = line.replace("P    ", "P A  ")
  					line = line.replace("P    ", "P A  ")
  					line = line.replace("P    ", "P A  ")
  					line = line.replace("P    ", "P A  ")
  					line = line.replace("P    ", "P A  ")
#   					
  					line = line.replace("R    ", "R A  ")
  					line = line.replace("R    ", "R A  ")
  					line = line.replace("R    ", "R A  ")
  					line = line.replace("R    ", "R A  ")
  					line = line.replace("R    ", "R A  ")
  					line = line.replace("R    ", "R A  ")
  					line = line.replace("R    ", "R A  ")
  					line = line.replace("R    ", "R A  ")
  					line = line.replace("R    ", "R A  ")
  					line = line.replace("R    ", "R A  ")
  					line = line.replace("R    ", "R A  ")
  					line = line.replace("R    ", "R A  ")
  					
  					line = line.replace("S    ", "S A  ")
  					line = line.replace("S    ", "S A  ")
  					line = line.replace("S    ", "S A  ")
  					line = line.replace("S    ", "S A  ")
  					line = line.replace("S    ", "S A  ")
  					line = line.replace("S    ", "S A  ")
  					line = line.replace("S    ", "S A  ")
  					line = line.replace("S    ", "S A  ")
  					line = line.replace("S    ", "S A  ")
  					line = line.replace("S    ", "S A  ")
  					line = line.replace("S    ", "S A  ")
  					line = line.replace("S    ", "S A  ")
  					
  					line = line.replace("T    ", "T A  ")
  					line = line.replace("T    ", "T A  ")
  					line = line.replace("T    ", "T A  ")
  					line = line.replace("T    ", "T A  ")
  					line = line.replace("T    ", "T A  ")
  					line = line.replace("T    ", "T A  ")
  					line = line.replace("T    ", "T A  ")
  					line = line.replace("T    ", "T A  ")
  					line = line.replace("T    ", "T A  ")
  					line = line.replace("T    ", "T A  ")
  					line = line.replace("T    ", "T A  ")
  					line = line.replace("T    ", "T A  ")
  					
  					line = line.replace("U    ", "U A  ")
  					line = line.replace("U    ", "U A  ")
  					line = line.replace("U    ", "U A  ")
  					line = line.replace("U    ", "U A  ")
  					line = line.replace("U    ", "U A  ")
  					line = line.replace("U    ", "U A  ")
  					line = line.replace("U    ", "U A  ")
  					line = line.replace("U    ", "U A  ")
  					line = line.replace("U    ", "U A  ")
  					line = line.replace("U    ", "U A  ")
  					line = line.replace("U    ", "U A  ")
  					line = line.replace("U    ", "U A  ")
  					
  					line = line.replace("Y    ", "Y A  ")
  					line = line.replace("Y    ", "Y A  ")
  					line = line.replace("Y    ", "Y A  ")
  					line = line.replace("Y    ", "Y A  ")
  					line = line.replace("Y    ", "Y A  ")
  					line = line.replace("Y    ", "Y A  ")
  					line = line.replace("Y    ", "Y A  ")
  					line = line.replace("Y    ", "Y A  ")
  					line = line.replace("Y    ", "Y A  ")
  					line = line.replace("Y    ", "Y A  ")
  					line = line.replace("Y    ", "Y A  ")
  					line = line.replace("Y    ", "Y A  ")
  										
  					line = line.replace("A     ", "A A   ")
  					line = line.replace("A     ", "A A   ")
  					line = line.replace("A     ", "A A   ")
  					line = line.replace("A     ", "A A   ")
  					line = line.replace("A     ", "A A   ")
  					line = line.replace("A     ", "A A   ")
  					line = line.replace("A     ", "A A   ")
  					line = line.replace("A     ", "A A   ")
  					line = line.replace("A     ", "A A   ")
  					line = line.replace("A     ", "A A   ")
  					line = line.replace("A     ", "A A   ")
  					line = line.replace("A     ", "A A   ")
  					
  					line = line.replace("E     ", "E A   ")
  					line = line.replace("E     ", "E A   ")
  					line = line.replace("E     ", "E A   ")
  					line = line.replace("E     ", "E A   ")
  					line = line.replace("E     ", "E A   ")
  					line = line.replace("E     ", "E A   ")
  					line = line.replace("E     ", "E A   ")
  					line = line.replace("E     ", "E A   ")
  					line = line.replace("E     ", "E A   ")
  					line = line.replace("E     ", "E A   ")
  					line = line.replace("E     ", "E A   ")
  					line = line.replace("E     ", "E A   ")
  					
  					line = line.replace("G     ", "G A   ")
  					line = line.replace("G     ", "G A   ")
  					line = line.replace("G     ", "G A   ")
  					line = line.replace("G     ", "G A   ")
  					line = line.replace("G     ", "G A   ")
  					line = line.replace("G     ", "G A   ")
  					line = line.replace("G     ", "G A   ")
  					line = line.replace("G     ", "G A   ")
  					line = line.replace("G     ", "G A   ")
  					line = line.replace("G     ", "G A   ")
  					line = line.replace("G     ", "G A   ")
  					line = line.replace("G     ", "G A   ")
  					
  					line = line.replace("L     ", "L A   ")
  					line = line.replace("L     ", "L A   ")
  					line = line.replace("L     ", "L A   ")
  					line = line.replace("L     ", "L A   ")
  					line = line.replace("L     ", "L A   ")
  					line = line.replace("L     ", "L A   ")
  					line = line.replace("L     ", "L A   ")
  					line = line.replace("L     ", "L A   ")
  					line = line.replace("L     ", "L A   ")
  					line = line.replace("L     ", "L A   ")
  					line = line.replace("L     ", "L A   ")
  					line = line.replace("L     ", "L A   ")
  					
  					line = line.replace("N     ", "N A   ")
  					line = line.replace("N     ", "N A   ")
  					line = line.replace("N     ", "N A   ")
  					line = line.replace("N     ", "N A   ")
  					line = line.replace("N     ", "N A   ")
  					line = line.replace("N     ", "N A   ")
  					line = line.replace("N     ", "N A   ")
  					line = line.replace("N     ", "N A   ")
  					line = line.replace("N     ", "N A   ")
  					line = line.replace("N     ", "N A   ")
  					line = line.replace("N     ", "N A   ")
  					line = line.replace("N     ", "N A   ")
  					
  					line = line.replace("O     ", "O A   ")
  					line = line.replace("O     ", "O A   ")
  					line = line.replace("O     ", "O A   ")
  					line = line.replace("O     ", "O A   ")
  					line = line.replace("O     ", "O A   ")
  					line = line.replace("O     ", "O A   ")
  					line = line.replace("O     ", "O A   ")
  					line = line.replace("O     ", "O A   ")
  					line = line.replace("O     ", "O A   ")
  					line = line.replace("O     ", "O A   ")
  					line = line.replace("O     ", "O A   ")
  					line = line.replace("O     ", "O A   ")
  					
  					line = line.replace("P     ", "P A   ")
  					line = line.replace("P     ", "P A   ")
  					line = line.replace("P     ", "P A   ")
  					line = line.replace("P     ", "P A   ")
  					line = line.replace("P     ", "P A   ")
  					line = line.replace("P     ", "P A   ")
  					line = line.replace("P     ", "P A   ")
  					line = line.replace("P     ", "P A   ")
  					line = line.replace("P     ", "P A   ")
  					line = line.replace("P     ", "P A   ")
  					line = line.replace("P     ", "P A   ")
  					line = line.replace("P     ", "P A   ")
#   					
  					line = line.replace("R     ", "R A   ")
  					line = line.replace("R     ", "R A   ")
  					line = line.replace("R     ", "R A   ")
  					line = line.replace("R     ", "R A   ")
  					line = line.replace("R     ", "R A   ")
  					line = line.replace("R     ", "R A   ")
  					line = line.replace("R     ", "R A   ")
  					line = line.replace("R     ", "R A   ")
  					line = line.replace("R     ", "R A   ")
  					line = line.replace("R     ", "R A   ")
  					line = line.replace("R     ", "R A   ")
  					line = line.replace("R     ", "R A   ")
#   					
  					line = line.replace("S     ", "S A   ")
  					line = line.replace("S     ", "S A   ")
  					line = line.replace("S     ", "S A   ")
  					line = line.replace("S     ", "S A   ")
  					line = line.replace("S     ", "S A   ")
  					line = line.replace("S     ", "S A   ")
  					line = line.replace("S     ", "S A   ")
  					line = line.replace("S     ", "S A   ")
  					line = line.replace("S     ", "S A   ")
  					line = line.replace("S     ", "S A   ")
  					line = line.replace("S     ", "S A   ")
  					line = line.replace("S     ", "S A   ")
  					
  					line = line.replace("T     ", "T A   ")
  					line = line.replace("T     ", "T A   ")
  					line = line.replace("T     ", "T A   ")
  					line = line.replace("T     ", "T A   ")
  					line = line.replace("T     ", "T A   ")
  					line = line.replace("T     ", "T A   ")
  					line = line.replace("T     ", "T A   ")
  					line = line.replace("T     ", "T A   ")
  					line = line.replace("T     ", "T A   ")
  					line = line.replace("T     ", "T A   ")
  					line = line.replace("T     ", "T A   ")
  					line = line.replace("T     ", "T A   ")
  					
  					line = line.replace("U     ", "U A   ")
  					line = line.replace("U     ", "U A   ")
  					line = line.replace("U     ", "U A   ")
  					line = line.replace("U     ", "U A   ")
  					line = line.replace("U     ", "U A   ")
  					line = line.replace("U     ", "U A   ")
  					line = line.replace("U     ", "U A   ")
  					line = line.replace("U     ", "U A   ")
  					line = line.replace("U     ", "U A   ")
  					line = line.replace("U     ", "U A   ")
  					line = line.replace("U     ", "U A   ")
  					line = line.replace("U     ", "U A   ")
  					
  					line = line.replace("Y     ", "Y A   ")
  					line = line.replace("Y     ", "Y A   ")
  					line = line.replace("Y     ", "Y A   ")
  					line = line.replace("Y     ", "Y A   ")
  					line = line.replace("Y     ", "Y A   ")
  					line = line.replace("Y     ", "Y A   ")
  					line = line.replace("Y     ", "Y A   ")
  					line = line.replace("Y     ", "Y A   ")
  					line = line.replace("Y     ", "Y A   ")
  					line = line.replace("Y     ", "Y A   ")
  					line = line.replace("Y     ", "Y A   ")
  					line = line.replace("Y     ", "Y A   ")	
  					
  					line = line.replace("N A A", "N   A")
  					line = line.replace("N A C", "N   C")
  					line = line.replace("N A G", "N   G")
  					line = line.replace("N A H", "N   H")
  					line = line.replace("N A I", "N   I")
  					line = line.replace("N A L", "N   L")
  					line = line.replace("N A M", "N   M")
  					line = line.replace("N A P", "N   P")
  					line = line.replace("N A S", "N   S")
  					line = line.replace("N A T", "N   T")
  					line = line.replace("N A V", "N   V")
  					
  					line = line.replace("O A A", "O   A")
  					line = line.replace("O A C", "O   C")
  					line = line.replace("O A G", "O   G")
  					line = line.replace("O A H", "O   H")
  					line = line.replace("O A I", "O   I")
  					line = line.replace("O A L", "O   L")
  					line = line.replace("O A M", "O   M")
  					line = line.replace("O A P", "O   P")
  					line = line.replace("O A S", "O   S")
  					line = line.replace("O A T", "O   T")
  					line = line.replace("O A V", "O   V")

  				# 	line = line.replace("T A A ", "T A   ")
#   					line = line.replace("U A A ", "T A   ")
#   					line = line.replace("O A A ", "T A   ")
#   					line = line.replace("A A A ", "T A   ")
#   					line = line.replace("L A A ", "T A   ")
#   					line = line.replace("Y A A ", "T A   ")
#   					line = line.replace("R A A ", "T A   ")
#   					line = line.replace("N A A ", "T A   ")
#   					line = line.replace("P A A ", "T A   ")
#   					line = line.replace("E A A ", "T A   ")
#   					line = line.replace("S A A ", "T A   ")
#   					line = line.replace("G A A ", "T A   ")
#   					
#   					
  					outFile.write(line)
  					#line = input.readline()
 					#print "Found it"
#   			
#				line = line.replace("HEADER", " ")
#   			line = line.replace("TITLE", " ")
#   			line = line.replace("COMPND", "\n")
#  			line = line.replace("HETATM", "ATOM  ")
#  			line = line.replace("1.00  0.00           C  ", "                        ")
#  			line = line.replace("1.00  0.00           N  ", "                        ")
#  			line = line.replace("1.00  0.00           O  ", "                        ")
#  			line = line.replace("1.00  0.00          Cl  ", "                        ")
#  			line = line.replace("1.00  0.00          Br  ", "                        ")
#  			line = line.replace("1.00  0.00           I  ", "                        ")
#  			line = line.replace("1.00  0.00           F  ", "                        ")
#  			line = line.replace("1.00  0.00           S  ", "                        ")
#  			line = line.replace("END", "\n")
#  			line = line.replace("1.00  0.00           H  ", "                        ")
#  			#line = input.readline()
#  			#print line		
  			
# 			
# 	
# 
main ()

# def main():
# 	
# 
# 	for i in range (1, 20):
# 			line = input.readline()
# 			words_2_delete = ['ANISOU']
# 			for line in input.readline():
#         			if not any(words_2_delete in line for words_2_delete in words_2_delete):
# 					outFile.write(line)
# 			
# 	
# 
# main ()

